# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sbPeakNeighborhoodSize = QtWidgets.QSpinBox(Form)
        self.sbPeakNeighborhoodSize.setAutoFillBackground(False)
        self.sbPeakNeighborhoodSize.setMinimum(10)
        self.sbPeakNeighborhoodSize.setMaximum(50)
        self.sbPeakNeighborhoodSize.setProperty("value", 20)
        self.sbPeakNeighborhoodSize.setObjectName("sbPeakNeighborhoodSize")
        self.horizontalLayout.addWidget(self.sbPeakNeighborhoodSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.sbFanValue = QtWidgets.QSpinBox(Form)
        self.sbFanValue.setMinimum(10)
        self.sbFanValue.setMaximum(50)
        self.sbFanValue.setProperty("value", 15)
        self.sbFanValue.setObjectName("sbFanValue")
        self.horizontalLayout_3.addWidget(self.sbFanValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spAmpMin = QtWidgets.QSpinBox(Form)
        self.spAmpMin.setProperty("value", 10)
        self.spAmpMin.setObjectName("spAmpMin")
        self.horizontalLayout_4.addWidget(self.spAmpMin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spLPF = QtWidgets.QSpinBox(Form)
        self.spLPF.setMaximum(20000)
        self.spLPF.setObjectName("spLPF")
        self.horizontalLayout_6.addWidget(self.spLPF)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.sbHPF = QtWidgets.QSpinBox(Form)
        self.sbHPF.setMaximum(20000)
        self.sbHPF.setObjectName("sbHPF")
        self.horizontalLayout_8.addWidget(self.sbHPF)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cb8k = QtWidgets.QCheckBox(Form)
        self.cb8k.setObjectName("cb8k")
        self.horizontalLayout_5.addWidget(self.cb8k)
        self.cb16k = QtWidgets.QCheckBox(Form)
        self.cb16k.setObjectName("cb16k")
        self.horizontalLayout_5.addWidget(self.cb16k)
        self.cb44k = QtWidgets.QCheckBox(Form)
        self.cb44k.setObjectName("cb44k")
        self.horizontalLayout_5.addWidget(self.cb44k)
        self.cb48k = QtWidgets.QCheckBox(Form)
        self.cb48k.setObjectName("cb48k")
        self.horizontalLayout_5.addWidget(self.cb48k)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.btnSelect = QtWidgets.QPushButton(Form)
        self.btnSelect.setCheckable(False)
        self.btnSelect.setObjectName("btnSelect")
        self.verticalLayout_2.addWidget(self.btnSelect)
        self.btnSave = QtWidgets.QPushButton(Form)
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout_2.addWidget(self.btnSave)
        self.lblInfo = QtWidgets.QPlainTextEdit(Form)
        self.lblInfo.setReadOnly(True)
        self.lblInfo.setObjectName("lblInfo")
        self.verticalLayout_2.addWidget(self.lblInfo)
        self.pbConvert = QtWidgets.QProgressBar(Form)
        self.pbConvert.setProperty("value", 0)
        self.pbConvert.setInvertedAppearance(False)
        self.pbConvert.setObjectName("pbConvert")
        self.verticalLayout_2.addWidget(self.pbConvert)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "PEAK_NEIGHBORHOOD_SIZE:"))
        self.label_2.setText(_translate("Form", "FAN_VALUE (degree of Finger Prints)"))
        self.label_3.setText(_translate("Form", "AMP_MIN (noise floor)"))
        self.label_4.setText(_translate("Form", "Low Pass Filter (Hz)"))
        self.label_5.setText(_translate("Form", "High Pass Filter (Hz)"))
        self.cb8k.setText(_translate("Form", "8KHz"))
        self.cb16k.setText(_translate("Form", "16KHz"))
        self.cb44k.setText(_translate("Form", "44.1KHz"))
        self.cb48k.setText(_translate("Form", "48KHz"))
        self.btnSelect.setText(_translate("Form", "Step1: Select an audio file (>= 3 channels) to generate finger prints"))
        self.btnSave.setText(_translate("Form", "Step 2: Select the path for saving the SQLite database of finger prints"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

